/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActividadesAcuaticasRouteImport } from './routes/actividades-acuaticas'
import { Route as LugaresParaVisitarRouteImport } from './routes/lugares-para-visitar'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesAcuaticasRoute = ActividadesAcuaticasRouteImport.update({
  id: '/actividades-acuaticas',
  path: '/actividades-acuaticas',
  getParentRoute: () => rootRouteImport,
} as any)
const LugaresParaVisitarRoute = LugaresParaVisitarRouteImport.update({
  id: '/lugares-para-visitar',
  path: '/lugares-para-visitar',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividades-acuaticas': typeof ActividadesAcuaticasRoute
  '/lugares-para-visitar': typeof LugaresParaVisitarRoute
  '/restaurantes': typeof RestaurantesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividades-acuaticas': typeof ActividadesAcuaticasRoute
  '/lugares-para-visitar': typeof LugaresParaVisitarRoute
  '/restaurantes': typeof RestaurantesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividades-acuaticas': typeof ActividadesAcuaticasRoute
  '/lugares-para-visitar': typeof LugaresParaVisitarRoute
  '/restaurantes': typeof RestaurantesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/actividades-acuaticas' | '/lugares-para-visitar' | '/restaurantes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/actividades-acuaticas' | '/lugares-para-visitar' | '/restaurantes'
  id:
    | '__root__'
    | '/'
    | '/actividades-acuaticas'
    | '/lugares-para-visitar'
    | '/restaurantes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadesAcuaticasRoute: typeof ActividadesAcuaticasRoute
  LugaresParaVisitarRoute: typeof LugaresParaVisitarRoute
  RestaurantesRoute: typeof RestaurantesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividades-acuaticas': {
      id: '/actividades-acuaticas'
      path: '/actividades-acuaticas'
      fullPath: '/actividades-acuaticas'
      preLoaderRoute: typeof ActividadesAcuaticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lugares-para-visitar': {
      id: '/lugares-para-visitar'
      path: '/lugares-para-visitar'
      fullPath: '/lugares-para-visitar'
      preLoaderRoute: typeof LugaresParaVisitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadesAcuaticasRoute: ActividadesAcuaticasRoute,
  LugaresParaVisitarRoute: LugaresParaVisitarRoute,
  RestaurantesRoute: RestaurantesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
